export const SET_LANG = "SET_LANG";
export const SET_POST_COULUMN_COUNT = "SET_POST_COULUMN_COUNT";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
